// SPDX-License-Identifier: MIT
using System.Text.Json;
using Auditarium.Bll.Abstractions.Identity;
using Auditarium.Bll.Abstractions.Persistence;
using Auditarium.Models.Identity;
using Auditarium.Models.Catalog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Auditarium.Dal;

public sealed class AuditariumDbContext : DbContext, IAuditariumDbContext
{
    private readonly ICurrentActor _currentActor;
    private bool _writingAuditLog;
    public AuditariumDbContext(DbContextOptions<AuditariumDbContext> options) : this(options, SystemCurrentActor.Instance) { }
    public AuditariumDbContext(DbContextOptions<AuditariumDbContext> options, ICurrentActor currentActor) : base(options) => _currentActor = currentActor;

    public DbSet<User> Users => Set<User>(); public DbSet<AuthenticationProvider> AuthenticationProviders => Set<AuthenticationProvider>(); public DbSet<UserIdentity> UserIdentities => Set<UserIdentity>(); public DbSet<LocalCredential> LocalCredentials => Set<LocalCredential>(); public DbSet<ApiCredential> ApiCredentials => Set<ApiCredential>(); public DbSet<Permission> Permissions => Set<Permission>(); public DbSet<Role> Roles => Set<Role>(); public DbSet<RolePermission> RolePermissions => Set<RolePermission>(); public DbSet<UserRole> UserRoles => Set<UserRole>(); public DbSet<ApplicationSetting> ApplicationSettings => Set<ApplicationSetting>(); public DbSet<SystemAuditLog> SystemAuditLogs => Set<SystemAuditLog>();
    public DbSet<Document> Documents => Set<Document>(); public DbSet<CatalogVersion> CatalogVersions => Set<CatalogVersion>(); public DbSet<DocumentElement> DocumentElements => Set<DocumentElement>(); public DbSet<DocumentElementWeight> DocumentElementWeights => Set<DocumentElementWeight>(); public DbSet<Question> Questions => Set<Question>(); public DbSet<ScopeType> ScopeTypes => Set<ScopeType>(); public DbSet<QuestionScopeType> QuestionScopeTypes => Set<QuestionScopeType>(); public DbSet<FileItem> FileItems => Set<FileItem>();
    public DbSet<AuditUnit> AuditUnits => Set<AuditUnit>(); public DbSet<Audit> Audits => Set<Audit>(); public DbSet<AuditDocumentElement> AuditDocumentElements => Set<AuditDocumentElement>(); public DbSet<AuditQuestion> AuditQuestions => Set<AuditQuestion>();

    protected override void OnModelCreating(ModelBuilder b)
    {
        b.HasDefaultSchema("auditarium");
        b.Entity<User>(e => { e.ToTable("users"); e.HasKey(x => x.UserId); e.Property(x => x.UserId).HasColumnName("user_id").ValueGeneratedOnAdd(); e.Property(x => x.UserKey).HasColumnName("user_key").HasMaxLength(64); e.HasIndex(x => x.UserKey).IsUnique().HasFilter("user_key IS NOT NULL"); e.Property(x => x.Username).HasColumnName("username").HasMaxLength(256); e.HasIndex(x => x.Username).IsUnique(); e.Property(x => x.DisplayName).HasColumnName("display_name").HasMaxLength(256); e.Property(x => x.Email).HasColumnName("email").HasMaxLength(320); Version(e.Property(x => x.ConcurrencyVersion)); });
        b.Entity<AuthenticationProvider>(e => { e.ToTable("authentication_providers"); e.HasKey(x => x.AuthenticationProviderId); e.Property(x => x.AuthenticationProviderId).HasColumnName("authentication_provider_id"); e.Property(x => x.ProviderKey).HasColumnName("provider_key").HasMaxLength(64); e.HasIndex(x => x.ProviderKey).IsUnique(); e.Property(x => x.ProviderType).HasColumnName("provider_type").HasMaxLength(64); e.Property(x => x.DisplayName).HasColumnName("display_name").HasMaxLength(256); Version(e.Property(x => x.ConcurrencyVersion)); });
        b.Entity<UserIdentity>(e => { e.ToTable("user_identities"); e.HasKey(x => x.IdentityId); e.Property(x => x.IdentityId).HasColumnName("identity_id"); e.Property(x => x.UserId).HasColumnName("user_id"); e.Property(x => x.AuthenticationProviderId).HasColumnName("authentication_provider_id"); e.Property(x => x.ExternalId).HasColumnName("external_id").HasMaxLength(256); e.HasIndex(x => new { x.AuthenticationProviderId, x.ExternalId }).IsUnique(); e.HasOne(x => x.User).WithMany(x => x.Identities).HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.AuthenticationProvider).WithMany().HasForeignKey(x => x.AuthenticationProviderId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<LocalCredential>(e => { e.ToTable("local_credentials"); e.HasKey(x => x.IdentityId); e.Property(x => x.IdentityId).HasColumnName("identity_id"); e.Property(x => x.PasswordHash).HasColumnName("password_hash"); e.Property(x => x.PasswordChangedAt).HasColumnName("password_changed_at"); e.Property(x => x.MustChangePassword).HasColumnName("must_change_password"); e.Property(x => x.FailedAttemptCount).HasColumnName("failed_attempt_count"); e.Property(x => x.FailedAttemptWindowStartedAt).HasColumnName("failed_attempt_window_started_at"); e.Property(x => x.LockoutUntil).HasColumnName("lockout_until"); e.HasOne(x => x.Identity).WithOne(x => x.LocalCredential).HasForeignKey<LocalCredential>(x => x.IdentityId).OnDelete(DeleteBehavior.Cascade); });
        b.Entity<ApiCredential>(e => { e.ToTable("api_credentials"); e.HasKey(x => x.ApiCredentialId); e.Property(x => x.ApiCredentialId).HasColumnName("api_credential_id"); e.Property(x => x.IdentityId).HasColumnName("identity_id"); e.Property(x => x.KeyId).HasColumnName("key_id").HasMaxLength(128); e.HasIndex(x => x.KeyId).IsUnique(); e.Property(x => x.SecretHash).HasColumnName("secret_hash"); e.Property(x => x.Name).HasColumnName("name").HasMaxLength(256); e.Property(x => x.CreatedAt).HasColumnName("created_at"); e.Property(x => x.ExpiresAt).HasColumnName("expires_at"); e.Property(x => x.RevokedAt).HasColumnName("revoked_at"); e.Property(x => x.LastUsedAt).HasColumnName("last_used_at"); e.HasOne(x => x.Identity).WithMany().HasForeignKey(x => x.IdentityId).OnDelete(DeleteBehavior.Cascade); });
        b.Entity<Permission>(e => { e.ToTable("permissions"); e.HasKey(x => x.PermissionKey); e.Property(x => x.PermissionKey).HasColumnName("permission_key").HasMaxLength(256); e.Property(x => x.Description).HasColumnName("description").HasMaxLength(512); });
        b.Entity<Role>(e => { e.ToTable("roles"); e.HasKey(x => x.RoleId); e.Property(x => x.RoleId).HasColumnName("role_id"); e.Property(x => x.RoleKey).HasColumnName("role_key").HasMaxLength(64); e.HasIndex(x => x.RoleKey).IsUnique().HasFilter("role_key IS NOT NULL"); e.Property(x => x.Name).HasColumnName("name").HasMaxLength(256); e.Property(x => x.Description).HasColumnName("description").HasMaxLength(512); Version(e.Property(x => x.ConcurrencyVersion)); });
        b.Entity<RolePermission>(e => { e.ToTable("role_permissions"); e.HasKey(x => new { x.RoleId, x.PermissionKey }); e.Property(x => x.RoleId).HasColumnName("role_id"); e.Property(x => x.PermissionKey).HasColumnName("permission_key").HasMaxLength(256); e.HasOne<Role>().WithMany().HasForeignKey(x => x.RoleId).OnDelete(DeleteBehavior.Cascade); e.HasOne<Permission>().WithMany().HasForeignKey(x => x.PermissionKey).OnDelete(DeleteBehavior.Cascade); });
        b.Entity<UserRole>(e => { e.ToTable("user_roles"); e.HasKey(x => new { x.UserId, x.RoleId }); e.Property(x => x.UserId).HasColumnName("user_id"); e.Property(x => x.RoleId).HasColumnName("role_id"); e.HasOne<User>().WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Restrict); e.HasOne<Role>().WithMany().HasForeignKey(x => x.RoleId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<ApplicationSetting>(e => { e.ToTable("application_settings"); e.HasKey(x => x.SettingKey); e.Property(x => x.SettingKey).HasColumnName("setting_key").HasMaxLength(256); e.Property(x => x.SerializedValue).HasColumnName("serialized_value"); Version(e.Property(x => x.ConcurrencyVersion)); });
        b.Entity<SystemAuditLog>(e => { e.ToTable("system_audit_log"); e.HasKey(x => x.EventId); e.Property(x => x.EventId).HasColumnName("event_id").ValueGeneratedOnAdd(); e.Property(x => x.OccurredAt).HasColumnName("occurred_at"); e.Property(x => x.UserId).HasColumnName("user_id"); e.Property(x => x.Action).HasColumnName("action").HasMaxLength(64); e.Property(x => x.ObjectType).HasColumnName("object_type").HasMaxLength(128); e.Property(x => x.ObjectId).HasColumnName("object_id"); e.Property(x => x.BeforeState).HasColumnName("before_state"); e.Property(x => x.AfterState).HasColumnName("after_state"); e.HasOne<User>().WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Restrict); e.HasIndex(x => new { x.ObjectType, x.ObjectId, x.Action, x.OccurredAt }); });
        b.Entity<Document>(e => { e.ToTable("documents"); e.HasKey(x => x.DocumentId); e.Property(x => x.DocumentId).HasColumnName("document_id").ValueGeneratedOnAdd(); e.Property(x => x.Title).HasColumnName("title").HasMaxLength(512); e.Property(x => x.Publisher).HasColumnName("publisher").HasMaxLength(512); e.Property(x => x.Version).HasColumnName("version").HasMaxLength(256); e.Property(x => x.PublicationDate).HasColumnName("publication_date"); e.Property(x => x.Source).HasColumnName("source").HasMaxLength(2048); e.Property(x => x.UsageState).HasColumnName("usage_state").HasConversion<string>().HasMaxLength(16); e.Property(x => x.UsageStateReason).HasColumnName("usage_state_reason"); e.Property(x => x.Notes).HasColumnName("notes"); Version(e.Property(x => x.ConcurrencyVersion)); e.ToTable(t => { t.HasCheckConstraint("ck_documents_usage_state", "usage_state IN ('Active', 'Deprecated')"); t.HasCheckConstraint("ck_documents_deprecated_reason", "usage_state <> 'Deprecated' OR usage_state_reason IS NOT NULL"); }); });
        b.Entity<FileItem>(e => { e.ToTable("file_items"); e.HasKey(x => x.FileId); e.Property(x => x.FileId).HasColumnName("file_id").ValueGeneratedOnAdd(); e.Property(x => x.OriginalFileName).HasColumnName("original_file_name").HasMaxLength(512); e.Property(x => x.SaveFileName).HasColumnName("save_file_name").HasMaxLength(64); e.Property(x => x.Extension).HasColumnName("extension").HasMaxLength(32); e.Property(x => x.SaveFilePath).HasColumnName("save_file_path").HasMaxLength(512); e.Property(x => x.ContentType).HasColumnName("content_type").HasMaxLength(256); e.Property(x => x.Size).HasColumnName("size"); e.Property(x => x.CreatedAt).HasColumnName("created_at"); e.Property(x => x.CreatedBy).HasColumnName("created_by"); e.Property(x => x.Checksum).HasColumnName("checksum").HasMaxLength(64); e.HasOne<User>().WithMany().HasForeignKey(x => x.CreatedBy).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<CatalogVersion>(e => { e.ToTable("catalog_versions"); e.HasKey(x => x.CatalogVersionId); e.Property(x => x.CatalogVersionId).HasColumnName("catalog_version_id").ValueGeneratedOnAdd(); e.Property(x => x.DocumentId).HasColumnName("document_id"); e.Property(x => x.VersionNumber).HasColumnName("version_number"); e.Property(x => x.CatalogState).HasColumnName("catalog_state").HasConversion<string>().HasMaxLength(16); e.Property(x => x.DraftRevision).HasColumnName("draft_revision"); e.Property(x => x.CreatedAt).HasColumnName("created_at"); e.Property(x => x.CreatedBy).HasColumnName("created_by"); e.Property(x => x.Notes).HasColumnName("notes"); e.Property(x => x.SourceFileId).HasColumnName("source_file_id"); Version(e.Property(x => x.ConcurrencyVersion)); e.HasIndex(x => new { x.DocumentId, x.VersionNumber }).IsUnique(); e.HasOne<Document>().WithMany().HasForeignKey(x => x.DocumentId).OnDelete(DeleteBehavior.Cascade); e.HasOne<User>().WithMany().HasForeignKey(x => x.CreatedBy).OnDelete(DeleteBehavior.Restrict); e.HasOne<FileItem>().WithMany().HasForeignKey(x => x.SourceFileId).OnDelete(DeleteBehavior.Restrict); e.ToTable(t => { t.HasCheckConstraint("ck_catalog_versions_numbers", "version_number >= 1 AND draft_revision >= 1"); t.HasCheckConstraint("ck_catalog_versions_state", "catalog_state IN ('Draft', 'Ready')"); }); });
        b.Entity<DocumentElement>(e => { e.ToTable("document_elements"); e.HasKey(x => x.ElementId); e.Property(x => x.ElementId).HasColumnName("element_id").ValueGeneratedOnAdd(); e.Property(x => x.CatalogVersionId).HasColumnName("catalog_version_id"); e.Property(x => x.ParentElementId).HasColumnName("parent_element_id"); e.Property(x => x.Title).HasColumnName("title"); e.Property(x => x.Text).HasColumnName("text"); e.Property(x => x.SortOrder).HasColumnName("sort_order"); e.Property(x => x.Notes).HasColumnName("notes"); e.HasOne<CatalogVersion>().WithMany().HasForeignKey(x => x.CatalogVersionId).OnDelete(DeleteBehavior.Cascade); e.HasOne(x => x.ParentElement).WithMany().HasForeignKey(x => x.ParentElementId).OnDelete(DeleteBehavior.Restrict); e.HasIndex(x => new { x.ParentElementId, x.SortOrder }).IsUnique().HasFilter("parent_element_id IS NOT NULL"); e.HasIndex(x => new { x.CatalogVersionId, x.SortOrder }).IsUnique().HasFilter("parent_element_id IS NULL"); e.ToTable(t => t.HasCheckConstraint("ck_document_elements_values", "sort_order >= 0 AND parent_element_id <> element_id AND (title IS NOT NULL OR text IS NOT NULL)")); });
        b.Entity<DocumentElementWeight>(e => { e.ToTable("document_element_weights"); e.HasKey(x => x.ElementId); e.Property(x => x.ElementId).HasColumnName("element_id"); e.Property(x => x.Weight).HasColumnName("weight"); e.HasOne(x => x.Element).WithMany().HasForeignKey(x => x.ElementId).OnDelete(DeleteBehavior.Cascade); e.ToTable(t => t.HasCheckConstraint("ck_document_element_weights_value", "weight IN (1, 2, 4, 5)")); });
        b.Entity<Question>(e => { e.ToTable("questions"); e.HasKey(x => x.QuestionId); e.Property(x => x.QuestionId).HasColumnName("question_id").ValueGeneratedOnAdd(); e.Property(x => x.ElementId).HasColumnName("element_id"); e.Property(x => x.SortOrder).HasColumnName("sort_order"); e.Property(x => x.Text).HasColumnName("text"); e.Property(x => x.VerificationHint).HasColumnName("verification_hint"); e.Property(x => x.EvidenceHint).HasColumnName("evidence_hint"); e.Property(x => x.Notes).HasColumnName("notes"); e.HasIndex(x => new { x.ElementId, x.SortOrder }).IsUnique(); e.HasOne(x => x.Element).WithMany().HasForeignKey(x => x.ElementId).OnDelete(DeleteBehavior.Cascade); e.ToTable(t => t.HasCheckConstraint("ck_questions_values", "sort_order >= 0 AND text <> ''")); });
        b.Entity<ScopeType>(e => { e.ToTable("scope_types"); e.HasKey(x => x.ScopeTypeId); e.Property(x => x.ScopeTypeId).HasColumnName("scope_type_id"); e.Property(x => x.Key).HasColumnName("key").HasMaxLength(64); e.Property(x => x.Name).HasColumnName("name").HasMaxLength(128); e.Property(x => x.Description).HasColumnName("description"); e.HasIndex(x => x.Key).IsUnique(); e.HasData(ScopeTypeSeed); });
        b.Entity<QuestionScopeType>(e => { e.ToTable("question_scope_types"); e.HasKey(x => new { x.QuestionId, x.ScopeTypeId }); e.Property(x => x.QuestionId).HasColumnName("question_id"); e.Property(x => x.ScopeTypeId).HasColumnName("scope_type_id"); e.HasOne(x => x.Question).WithMany().HasForeignKey(x => x.QuestionId).OnDelete(DeleteBehavior.Cascade); e.HasOne(x => x.ScopeType).WithMany().HasForeignKey(x => x.ScopeTypeId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<AuditUnit>(e => { e.ToTable("audit_units"); e.HasKey(x => x.AuditUnitId); e.Property(x => x.AuditUnitId).HasColumnName("audit_unit_id").ValueGeneratedOnAdd(); e.Property(x => x.ParentAuditUnitId).HasColumnName("parent_audit_unit_id"); e.Property(x => x.ScopeTypeId).HasColumnName("scope_type_id"); e.Property(x => x.Name).HasColumnName("name").HasMaxLength(512); e.Property(x => x.Description).HasColumnName("description"); e.Property(x => x.UsageState).HasColumnName("usage_state").HasConversion<string>().HasMaxLength(16); e.Property(x => x.UsageStateReason).HasColumnName("usage_state_reason"); e.Property(x => x.Notes).HasColumnName("notes"); Version(e.Property(x => x.ConcurrencyVersion)); e.HasOne<AuditUnit>().WithMany().HasForeignKey(x => x.ParentAuditUnitId).OnDelete(DeleteBehavior.Restrict); e.HasOne<ScopeType>().WithMany().HasForeignKey(x => x.ScopeTypeId).OnDelete(DeleteBehavior.Restrict); e.ToTable(t => t.HasCheckConstraint("ck_audit_units_values", "parent_audit_unit_id <> audit_unit_id AND usage_state IN ('Active', 'Inactive') AND (usage_state <> 'Inactive' OR usage_state_reason IS NOT NULL)")); });
        b.Entity<Audit>(e => { e.ToTable("audits"); e.HasKey(x => x.AuditId); e.Property(x => x.AuditId).HasColumnName("audit_id").ValueGeneratedOnAdd(); e.Property(x => x.OriginAuditId).HasColumnName("origin_audit_id"); e.Property(x => x.Name).HasColumnName("name").HasMaxLength(512); e.Property(x => x.Description).HasColumnName("description"); e.Property(x => x.AuditUnitId).HasColumnName("audit_unit_id"); e.Property(x => x.CatalogVersionId).HasColumnName("catalog_version_id"); e.Property(x => x.AuditUnitContext).HasColumnName("audit_unit_context"); e.Property(x => x.AuditState).HasColumnName("audit_state").HasConversion<string>().HasMaxLength(16); e.Property(x => x.StateReason).HasColumnName("state_reason"); e.Property(x => x.AssignedAuditorUserId).HasColumnName("assigned_auditor_user_id"); e.Property(x => x.AuditSettings).HasColumnName("audit_settings"); e.Property(x => x.CreatedAt).HasColumnName("created_at"); e.Property(x => x.Notes).HasColumnName("notes"); Version(e.Property(x => x.ConcurrencyVersion)); e.HasOne<Audit>().WithMany().HasForeignKey(x => x.OriginAuditId).OnDelete(DeleteBehavior.Restrict); e.HasOne<AuditUnit>().WithMany().HasForeignKey(x => x.AuditUnitId).OnDelete(DeleteBehavior.Restrict); e.HasOne<CatalogVersion>().WithMany().HasForeignKey(x => x.CatalogVersionId).OnDelete(DeleteBehavior.Restrict); e.HasOne<User>().WithMany().HasForeignKey(x => x.AssignedAuditorUserId).OnDelete(DeleteBehavior.Restrict); e.ToTable(t => t.HasCheckConstraint("ck_audits_values", "origin_audit_id <> audit_id AND audit_state IN ('Draft', 'Ready', 'InProgress', 'Finalized', 'Canceled') AND ((audit_state = 'Draft' AND audit_unit_context IS NULL AND assigned_auditor_user_id IS NULL) OR audit_state <> 'Draft') AND (audit_state = 'Draft' OR audit_unit_context IS NOT NULL) AND (audit_state <> 'Finalized' OR assigned_auditor_user_id IS NULL) AND (audit_state <> 'Canceled' OR state_reason IS NOT NULL)")); });
        b.Entity<AuditDocumentElement>(e => { e.ToTable("audit_document_elements"); e.HasKey(x => x.AuditDocumentElementId); e.Property(x => x.AuditDocumentElementId).HasColumnName("audit_document_element_id").ValueGeneratedOnAdd(); e.Property(x => x.AuditId).HasColumnName("audit_id"); e.Property(x => x.ElementId).HasColumnName("element_id"); e.Property(x => x.WeightSnapshot).HasColumnName("weight_snapshot"); e.HasIndex(x => new { x.AuditId, x.ElementId }).IsUnique(); e.HasOne<Audit>().WithMany().HasForeignKey(x => x.AuditId).OnDelete(DeleteBehavior.Cascade); e.HasOne<DocumentElement>().WithMany().HasForeignKey(x => x.ElementId).OnDelete(DeleteBehavior.Restrict); e.ToTable(t => t.HasCheckConstraint("ck_audit_document_elements_weight", "weight_snapshot BETWEEN 1 AND 5")); });
        b.Entity<AuditQuestion>(e => { e.ToTable("audit_questions"); e.HasKey(x => x.AuditQuestionId); e.Property(x => x.AuditQuestionId).HasColumnName("audit_question_id").ValueGeneratedOnAdd(); e.Property(x => x.AuditDocumentElementId).HasColumnName("audit_document_element_id"); e.Property(x => x.QuestionId).HasColumnName("question_id"); e.Property(x => x.Result).HasColumnName("result").HasConversion<string>().HasMaxLength(32); e.Property(x => x.Comment).HasColumnName("comment"); e.Property(x => x.Evidence).HasColumnName("evidence"); e.Property(x => x.AnsweredAt).HasColumnName("answered_at"); e.Property(x => x.AnsweredBy).HasColumnName("answered_by"); Version(e.Property(x => x.ConcurrencyVersion)); e.HasIndex(x => new { x.AuditDocumentElementId, x.QuestionId }).IsUnique(); e.HasOne<AuditDocumentElement>().WithMany().HasForeignKey(x => x.AuditDocumentElementId).OnDelete(DeleteBehavior.Cascade); e.HasOne<Question>().WithMany().HasForeignKey(x => x.QuestionId).OnDelete(DeleteBehavior.Restrict); e.HasOne<User>().WithMany().HasForeignKey(x => x.AnsweredBy).OnDelete(DeleteBehavior.Restrict); e.ToTable(t => t.HasCheckConstraint("ck_audit_questions_answer", "(result IS NULL AND comment IS NULL AND evidence IS NULL AND answered_at IS NULL AND answered_by IS NULL) OR (result IS NOT NULL AND answered_at IS NOT NULL AND answered_by IS NOT NULL)")); });
    }

    public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        if (_writingAuditLog) return await base.SaveChangesAsync(cancellationToken);
        foreach (var entry in ChangeTracker.Entries().Where(x => x.State == EntityState.Modified)) { var version = entry.Metadata.FindProperty("ConcurrencyVersion"); if (version is not null) entry.Property("ConcurrencyVersion").CurrentValue = ((long)entry.Property("ConcurrencyVersion").OriginalValue!) + 1; }
        var changes = ChangeTracker.Entries().Where(e => e.Entity is not SystemAuditLog && e.State is EntityState.Added or EntityState.Modified or EntityState.Deleted).Select(AuditChange.Create).ToList();
        if (changes.Count == 0 || !await Users.AsNoTracking().AnyAsync(x => x.UserId == 0, cancellationToken)) return await base.SaveChangesAsync(cancellationToken);
        var transaction = Database.CurrentTransaction;
        var ownsTransaction = transaction is null;
        if (ownsTransaction) transaction = await Database.BeginTransactionAsync(cancellationToken);
        else await transaction!.CreateSavepointAsync("auditarium_save_changes", cancellationToken);
        try
        {
            var result = await base.SaveChangesAsync(cancellationToken);
            foreach (var change in changes) SystemAuditLogs.Add(change.ToLog(_currentActor.UserId ?? 0));
            _writingAuditLog = true; await base.SaveChangesAsync(cancellationToken); _writingAuditLog = false;
            if (ownsTransaction) await transaction!.CommitAsync(cancellationToken);
            return result;
        }
        catch
        {
            _writingAuditLog = false;
            if (ownsTransaction) await transaction!.RollbackAsync(cancellationToken);
            else await transaction!.RollbackToSavepointAsync("auditarium_save_changes", cancellationToken);
            throw;
        }
        finally { if (ownsTransaction && transaction is not null) await transaction.DisposeAsync(); }
    }

    private static void Version(PropertyBuilder<long> p) => p.HasColumnName("concurrency_version").IsConcurrencyToken().HasDefaultValue(1);

    private static readonly ScopeType[] ScopeTypeSeed =
    [
        new() { ScopeTypeId = 1, Key = "ORGANIZATION", Name = "Organisation", Description = "Organisatorisch abgegrenzte Gesamteinheit." }, new() { ScopeTypeId = 2, Key = "SITE", Name = "Standort", Description = "Räumlich zusammenhängende Betriebsstätte." }, new() { ScopeTypeId = 3, Key = "BUILDING", Name = "Gebäude", Description = "Einzelnes baulich abgegrenztes Gebäude." }, new() { ScopeTypeId = 4, Key = "AREA", Name = "Bereich", Description = "Organisatorisch oder funktional abgegrenzter Bereich." }, new() { ScopeTypeId = 5, Key = "ROOM", Name = "Raum", Description = "Einzelner räumlich abgegrenzter Raum." }, new() { ScopeTypeId = 6, Key = "TECHNICAL_AREA", Name = "Technikbereich", Description = "Bereich für technische Infrastruktur." }, new() { ScopeTypeId = 7, Key = "NETWORK", Name = "Netzwerk", Description = "Abgegrenzte Kommunikationsinfrastruktur." }, new() { ScopeTypeId = 8, Key = "IT_SYSTEM", Name = "IT-System", Description = "Konkretes technisches System oder Plattform." }, new() { ScopeTypeId = 9, Key = "APPLICATION", Name = "Anwendung", Description = "Softwareanwendung oder Softwaresystem." }, new() { ScopeTypeId = 10, Key = "PROCESS", Name = "Prozess", Description = "Definierter organisatorischer oder technischer Ablauf." }, new() { ScopeTypeId = 11, Key = "SERVICE", Name = "Dienst / Service", Description = "Bereitgestellte technische oder organisatorische Leistung." }, new() { ScopeTypeId = 12, Key = "EXTERNAL_PROVIDER", Name = "Externer Dienstleister", Description = "Externe Organisation oder Vertragspartner." }, new() { ScopeTypeId = 13, Key = "OTHER", Name = "Sonstiges", Description = "Nur verwenden, wenn kein anderer Scope Type passt." }
    ];

    private sealed record AuditChange(EntityEntry Entry, string Action, string ObjectType, Dictionary<string, object?> Before, Dictionary<string, object?> After)
    {
        private static readonly IReadOnlyDictionary<string, string[]> Allowed = new Dictionary<string, string[]>(StringComparer.Ordinal) { [nameof(User)] = [nameof(User.IsActive)], [nameof(AuthenticationProvider)] = [nameof(AuthenticationProvider.ProviderKey), nameof(AuthenticationProvider.ProviderType), nameof(AuthenticationProvider.IsEnabled)], [nameof(Role)] = [nameof(Role.RoleKey), nameof(Role.Name), nameof(Role.Description), nameof(Role.IsActive)], [nameof(Permission)] = [nameof(Permission.PermissionKey), nameof(Permission.Description), nameof(Permission.IsActive)], [nameof(ApiCredential)] = [nameof(ApiCredential.Name), nameof(ApiCredential.CreatedAt), nameof(ApiCredential.ExpiresAt), nameof(ApiCredential.RevokedAt)], [nameof(ApplicationSetting)] = [nameof(ApplicationSetting.SettingKey)], [nameof(Document)] = [nameof(Document.Title), nameof(Document.Publisher), nameof(Document.Version), nameof(Document.PublicationDate), nameof(Document.Source), nameof(Document.UsageState), nameof(Document.UsageStateReason), nameof(Document.Notes)], [nameof(CatalogVersion)] = [nameof(CatalogVersion.CatalogState), nameof(CatalogVersion.DraftRevision), nameof(CatalogVersion.Notes), nameof(CatalogVersion.SourceFileId)], [nameof(DocumentElement)] = [nameof(DocumentElement.ParentElementId), nameof(DocumentElement.Title), nameof(DocumentElement.Text), nameof(DocumentElement.SortOrder), nameof(DocumentElement.Notes)], [nameof(DocumentElementWeight)] = [nameof(DocumentElementWeight.Weight)], [nameof(Question)] = [nameof(Question.SortOrder), nameof(Question.Text), nameof(Question.VerificationHint), nameof(Question.EvidenceHint), nameof(Question.Notes)] };
        public static AuditChange Create(EntityEntry entry)
        {
            var before = new Dictionary<string, object?>(); var after = new Dictionary<string, object?>(); var type = entry.Metadata.ClrType.Name;
            if (Allowed.TryGetValue(type, out var allowed)) foreach (var p in entry.Properties.Where(p => allowed.Contains(p.Metadata.Name, StringComparer.Ordinal) && (entry.State != EntityState.Modified || p.IsModified))) { if (entry.State is EntityState.Modified or EntityState.Deleted) before[AuditPropertyName(p.Metadata.Name)] = p.OriginalValue; if (entry.State is EntityState.Modified or EntityState.Added) after[AuditPropertyName(p.Metadata.Name)] = p.CurrentValue; }
            var action = entry.State == EntityState.Added ? "CREATED" : entry.State == EntityState.Deleted ? "PURGED" : type == nameof(Audit) && entry.Property(nameof(Audit.AuditState)).IsModified ? "STATE_CHANGED" : "UPDATED";
            return new(entry, action, type, before, after);
        }
        public SystemAuditLog ToLog(long actor) { AuditLogContract.Validate(Action, ObjectType); return new() { OccurredAt = DateTimeOffset.UtcNow, UserId = actor, Action = Action, ObjectType = ObjectType, ObjectId = Id(Entry), BeforeState = Before.Count == 0 ? null : JsonSerializer.Serialize(Before), AfterState = After.Count == 0 ? null : JsonSerializer.Serialize(After) }; }
        private static long? Id(EntityEntry entry) { var key = entry.Metadata.FindPrimaryKey(); return key?.Properties.Count == 1 && entry.Property(key.Properties[0].Name).CurrentValue is long id ? id : null; }
        private static string AuditPropertyName(string name) => string.Concat(name.Select((character, index) => index > 0 && char.IsUpper(character) ? "_" + char.ToLowerInvariant(character) : char.ToLowerInvariant(character).ToString()));
    }
    private sealed class SystemCurrentActor : ICurrentActor { public static readonly SystemCurrentActor Instance = new(); public ActorType Type => ActorType.System; public long? UserId => 0; public bool IsAuthenticated => true; }
}
