// <auto-generated />
using System;
using Auditarium.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Auditarium.Dal.PostgreSql.Migrations.Migrations
{
    [DbContext(typeof(AuditariumDbContext))]
    [Migration("20260922195935_AddSoftDeleteRetention")]
    partial class AddSoftDeleteRetention
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("auditarium")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Auditarium.Models.Catalog.Audit", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditId"));

                    b.Property<long?>("AssignedAuditorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_auditor_user_id");

                    b.Property<string>("AuditSettings")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("audit_settings");

                    b.Property<string>("AuditState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("audit_state");

                    b.Property<string>("AuditUnitContext")
                        .HasColumnType("text")
                        .HasColumnName("audit_unit_context");

                    b.Property<long>("AuditUnitId")
                        .HasColumnType("bigint")
                        .HasColumnName("audit_unit_id");

                    b.Property<long>("CatalogVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("catalog_version_id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("text")
                        .HasColumnName("deletion_reason");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<long?>("OriginAuditId")
                        .HasColumnType("bigint")
                        .HasColumnName("origin_audit_id");

                    b.Property<string>("StateReason")
                        .HasColumnType("text")
                        .HasColumnName("state_reason");

                    b.HasKey("AuditId");

                    b.HasIndex("AssignedAuditorUserId");

                    b.HasIndex("AuditUnitId");

                    b.HasIndex("CatalogVersionId");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("OriginAuditId");

                    b.ToTable("audits", "auditarium", t =>
                        {
                            t.HasCheckConstraint("ck_audits_soft_delete", "(deleted_at IS NULL AND deleted_by IS NULL AND deletion_reason IS NULL) OR (deleted_at IS NOT NULL AND deleted_by IS NOT NULL)");

                            t.HasCheckConstraint("ck_audits_values", "origin_audit_id <> audit_id AND audit_state IN ('Draft', 'Ready', 'InProgress', 'Finalized', 'Canceled') AND ((audit_state = 'Draft' AND audit_unit_context IS NULL AND assigned_auditor_user_id IS NULL) OR audit_state <> 'Draft') AND (audit_state = 'Draft' OR audit_unit_context IS NOT NULL) AND (audit_state <> 'Finalized' OR assigned_auditor_user_id IS NULL) AND (audit_state <> 'Canceled' OR state_reason IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Auditarium.Models.Catalog.AuditDocumentElement", b =>
                {
                    b.Property<long>("AuditDocumentElementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_document_element_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditDocumentElementId"));

                    b.Property<long>("AuditId")
                        .HasColumnType("bigint")
                        .HasColumnName("audit_id");

                    b.Property<long>("ElementId")
                        .HasColumnType("bigint")
                        .HasColumnName("element_id");

                    b.Property<int>("WeightSnapshot")
                        .HasColumnType("integer")
                        .HasColumnName("weight_snapshot");

                    b.HasKey("AuditDocumentElementId");

                    b.HasIndex("ElementId");

                    b.HasIndex("AuditId", "ElementId")
                        .IsUnique();

                    b.ToTable("audit_document_elements", "auditarium", t =>
                        {
                            t.HasCheckConstraint("ck_audit_document_elements_weight", "weight_snapshot BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Auditarium.Models.Catalog.AuditQuestion", b =>
                {
                    b.Property<long>("AuditQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_question_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditQuestionId"));

                    b.Property<DateTimeOffset?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<long?>("AnsweredBy")
                        .HasColumnType("bigint")
                        .HasColumnName("answered_by");

                    b.Property<long>("AuditDocumentElementId")
                        .HasColumnType("bigint")
                        .HasColumnName("audit_document_element_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<string>("Evidence")
                        .HasColumnType("text")
                        .HasColumnName("evidence");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    b.Property<string>("Result")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("result");

                    b.HasKey("AuditQuestionId");

                    b.HasIndex("AnsweredBy");

                    b.HasIndex("QuestionId");

                    b.HasIndex("AuditDocumentElementId", "QuestionId")
                        .IsUnique();

                    b.ToTable("audit_questions", "auditarium", t =>
                        {
                            t.HasCheckConstraint("ck_audit_questions_answer", "(result IS NULL AND comment IS NULL AND evidence IS NULL AND answered_at IS NULL AND answered_by IS NULL) OR (result IS NOT NULL AND answered_at IS NOT NULL AND answered_by IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Auditarium.Models.Catalog.AuditUnit", b =>
                {
                    b.Property<long>("AuditUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_unit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditUnitId"));

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("text")
                        .HasColumnName("deletion_reason");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<long?>("ParentAuditUnitId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_audit_unit_id");

                    b.Property<long>("ScopeTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("scope_type_id");

                    b.Property<string>("UsageState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("usage_state");

                    b.Property<string>("UsageStateReason")
                        .HasColumnType("text")
                        .HasColumnName("usage_state_reason");

                    b.HasKey("AuditUnitId");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ParentAuditUnitId");

                    b.HasIndex("ScopeTypeId");

                    b.ToTable("audit_units", "auditarium", t =>
                        {
                            t.HasCheckConstraint("ck_audit_units_soft_delete", "(deleted_at IS NULL AND deleted_by IS NULL AND deletion_reason IS NULL) OR (deleted_at IS NOT NULL AND deleted_by IS NOT NULL)");

                            t.HasCheckConstraint("ck_audit_units_values", "parent_audit_unit_id <> audit_unit_id AND usage_state IN ('Active', 'Inactive') AND (usage_state <> 'Inactive' OR usage_state_reason IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Auditarium.Models.Catalog.CatalogVersion", b =>
                {
                    b.Property<long>("CatalogVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("catalog_version_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CatalogVersionId"));

                    b.Property<string>("CatalogState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("catalog_state");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("document_id");

                    b.Property<int>("DraftRevision")
                        .HasColumnType("integer")
                        .HasColumnName("draft_revision");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<long?>("SourceFileId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_file_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("CatalogVersionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SourceFileId");

                    b.HasIndex("DocumentId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("catalog_versions", "auditarium", t =>
                        {
                            t.HasCheckConstraint("ck_catalog_versions_numbers", "version_number >= 1 AND draft_revision >= 1");

                            t.HasCheckConstraint("ck_catalog_versions_state", "catalog_state IN ('Draft', 'Ready')");
                        });
                });

            modelBuilder.Entity("Auditarium.Models.Catalog.Document", b =>
                {
                    b.Property<long>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("document_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DocumentId"));

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("text")
                        .HasColumnName("deletion_reason");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly?>("PublicationDate")
                        .HasColumnType("date")
                        .HasColumnName("publication_date");

                    b.Property<string>("Publisher")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("publisher");

                    b.Property<string>("Source")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<string>("UsageState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("usage_state");

                    b.Property<string>("UsageStateReason")
                        .HasColumnType("text")
                        .HasColumnName("usage_state_reason");

                    b.Property<string>("Version")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("version");

                    b.HasKey("DocumentId");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("DeletedBy");

                    b.ToTable("documents", "auditarium", t =>
                        {
                            t.HasCheckConstraint("ck_documents_deprecated_reason", "usage_state <> 'Deprecated' OR usage_state_reason IS NOT NULL");

                            t.HasCheckConstraint("ck_documents_soft_delete", "(deleted_at IS NULL AND deleted_by IS NULL AND deletion_reason IS NULL) OR (deleted_at IS NOT NULL AND deleted_by IS NOT NULL)");

                            t.HasCheckConstraint("ck_documents_usage_state", "usage_state IN ('Active', 'Deprecated')");
                        });
                });

            modelBuilder.Entity("Auditarium.Models.Catalog.DocumentElement", b =>
                {
                    b.Property<long>("ElementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("element_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ElementId"));

                    b.Property<long>("CatalogVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("catalog_version_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<long?>("ParentElementId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_element_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("ElementId");

                    b.HasIndex("CatalogVersionId", "SortOrder")
                        .IsUnique()
                        .HasFilter("parent_element_id IS NULL");

                    b.HasIndex("ParentElementId", "SortOrder")
                        .IsUnique()
                        .HasFilter("parent_element_id IS NOT NULL");

                    b.ToTable("document_elements", "auditarium", t =>
                        {
                            t.HasCheckConstraint("ck_document_elements_values", "sort_order >= 0 AND parent_element_id <> element_id AND (title IS NOT NULL OR text IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Auditarium.Models.Catalog.DocumentElementWeight", b =>
                {
                    b.Property<long>("ElementId")
                        .HasColumnType("bigint")
                        .HasColumnName("element_id");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("ElementId");

                    b.ToTable("document_element_weights", "auditarium", t =>
                        {
                            t.HasCheckConstraint("ck_document_element_weights_value", "weight IN (1, 2, 4, 5)");
                        });
                });

            modelBuilder.Entity("Auditarium.Models.Catalog.FileItem", b =>
                {
                    b.Property<long>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("file_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FileId"));

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("checksum");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("extension");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("SaveFileName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("save_file_name");

                    b.Property<string>("SaveFilePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("save_file_path");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.HasKey("FileId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("file_items", "auditarium");
                });

            modelBuilder.Entity("Auditarium.Models.Catalog.Question", b =>
                {
                    b.Property<long>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("QuestionId"));

                    b.Property<long>("ElementId")
                        .HasColumnType("bigint")
                        .HasColumnName("element_id");

                    b.Property<string>("EvidenceHint")
                        .HasColumnType("text")
                        .HasColumnName("evidence_hint");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("VerificationHint")
                        .HasColumnType("text")
                        .HasColumnName("verification_hint");

                    b.HasKey("QuestionId");

                    b.HasIndex("ElementId", "SortOrder")
                        .IsUnique();

                    b.ToTable("questions", "auditarium", t =>
                        {
                            t.HasCheckConstraint("ck_questions_values", "sort_order >= 0 AND text <> ''");
                        });
                });

            modelBuilder.Entity("Auditarium.Models.Catalog.QuestionScopeType", b =>
                {
                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    b.Property<long>("ScopeTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("scope_type_id");

                    b.HasKey("QuestionId", "ScopeTypeId");

                    b.HasIndex("ScopeTypeId");

                    b.ToTable("question_scope_types", "auditarium");
                });

            modelBuilder.Entity("Auditarium.Models.Catalog.ScopeType", b =>
                {
                    b.Property<long>("ScopeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("scope_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ScopeTypeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("ScopeTypeId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("scope_types", "auditarium");

                    b.HasData(
                        new
                        {
                            ScopeTypeId = 1L,
                            Description = "Organisatorisch abgegrenzte Gesamteinheit.",
                            Key = "ORGANIZATION",
                            Name = "Organisation"
                        },
                        new
                        {
                            ScopeTypeId = 2L,
                            Description = "Räumlich zusammenhängende Betriebsstätte.",
                            Key = "SITE",
                            Name = "Standort"
                        },
                        new
                        {
                            ScopeTypeId = 3L,
                            Description = "Einzelnes baulich abgegrenztes Gebäude.",
                            Key = "BUILDING",
                            Name = "Gebäude"
                        },
                        new
                        {
                            ScopeTypeId = 4L,
                            Description = "Organisatorisch oder funktional abgegrenzter Bereich.",
                            Key = "AREA",
                            Name = "Bereich"
                        },
                        new
                        {
                            ScopeTypeId = 5L,
                            Description = "Einzelner räumlich abgegrenzter Raum.",
                            Key = "ROOM",
                            Name = "Raum"
                        },
                        new
                        {
                            ScopeTypeId = 6L,
                            Description = "Bereich für technische Infrastruktur.",
                            Key = "TECHNICAL_AREA",
                            Name = "Technikbereich"
                        },
                        new
                        {
                            ScopeTypeId = 7L,
                            Description = "Abgegrenzte Kommunikationsinfrastruktur.",
                            Key = "NETWORK",
                            Name = "Netzwerk"
                        },
                        new
                        {
                            ScopeTypeId = 8L,
                            Description = "Konkretes technisches System oder Plattform.",
                            Key = "IT_SYSTEM",
                            Name = "IT-System"
                        },
                        new
                        {
                            ScopeTypeId = 9L,
                            Description = "Softwareanwendung oder Softwaresystem.",
                            Key = "APPLICATION",
                            Name = "Anwendung"
                        },
                        new
                        {
                            ScopeTypeId = 10L,
                            Description = "Definierter organisatorischer oder technischer Ablauf.",
                            Key = "PROCESS",
                            Name = "Prozess"
                        },
                        new
                        {
                            ScopeTypeId = 11L,
                            Description = "Bereitgestellte technische oder organisatorische Leistung.",
                            Key = "SERVICE",
                            Name = "Dienst / Service"
                        },
                        new
                        {
                            ScopeTypeId = 12L,
                            Description = "Externe Organisation oder Vertragspartner.",
                            Key = "EXTERNAL_PROVIDER",
                            Name = "Externer Dienstleister"
                        },
                        new
                        {
                            ScopeTypeId = 13L,
                            Description = "Nur verwenden, wenn kein anderer Scope Type passt.",
                            Key = "OTHER",
                            Name = "Sonstiges"
                        });
                });

            modelBuilder.Entity("Auditarium.Models.Identity.ApiCredential", b =>
                {
                    b.Property<long>("ApiCredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("api_credential_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ApiCredentialId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long>("IdentityId")
                        .HasColumnType("bigint")
                        .HasColumnName("identity_id");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key_id");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("secret_hash");

                    b.HasKey("ApiCredentialId");

                    b.HasIndex("IdentityId");

                    b.HasIndex("KeyId")
                        .IsUnique();

                    b.ToTable("api_credentials", "auditarium");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.ApplicationSetting", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("setting_key");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<string>("SerializedValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serialized_value");

                    b.HasKey("SettingKey");

                    b.ToTable("application_settings", "auditarium");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.AuthenticationProvider", b =>
                {
                    b.Property<long>("AuthenticationProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("authentication_provider_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuthenticationProviderId"));

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_type");

                    b.HasKey("AuthenticationProviderId");

                    b.HasIndex("ProviderKey")
                        .IsUnique();

                    b.ToTable("authentication_providers", "auditarium");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.LocalCredential", b =>
                {
                    b.Property<long>("IdentityId")
                        .HasColumnType("bigint")
                        .HasColumnName("identity_id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<int>("FailedAttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempt_count");

                    b.Property<DateTimeOffset?>("FailedAttemptWindowStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_attempt_window_started_at");

                    b.Property<DateTimeOffset?>("LockoutUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_until");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<DateTimeOffset?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("IdentityId");

                    b.ToTable("local_credentials", "auditarium");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.Permission", b =>
                {
                    b.Property<string>("PermissionKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("permission_key");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("PermissionKey");

                    b.ToTable("permissions", "auditarium");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RoleId"));

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("RoleKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role_key");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleKey")
                        .IsUnique()
                        .HasFilter("role_key IS NOT NULL");

                    b.ToTable("roles", "auditarium");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.RolePermission", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<string>("PermissionKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("permission_key");

                    b.HasKey("RoleId", "PermissionKey");

                    b.HasIndex("PermissionKey");

                    b.ToTable("role_permissions", "auditarium");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.SystemAuditLog", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EventId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("AfterState")
                        .HasColumnType("text")
                        .HasColumnName("after_state");

                    b.Property<string>("BeforeState")
                        .HasColumnType("text")
                        .HasColumnName("before_state");

                    b.Property<long?>("ObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("object_id");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("object_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("EventId");

                    b.HasIndex("UserId");

                    b.HasIndex("ObjectType", "ObjectId", "Action", "OccurredAt");

                    b.ToTable("system_audit_log", "auditarium");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("UserKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_key");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("UserKey")
                        .IsUnique()
                        .HasFilter("user_key IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", "auditarium");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.UserIdentity", b =>
                {
                    b.Property<long>("IdentityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("identity_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdentityId"));

                    b.Property<long>("AuthenticationProviderId")
                        .HasColumnType("bigint")
                        .HasColumnName("authentication_provider_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("IdentityId");

                    b.HasIndex("UserId");

                    b.HasIndex("AuthenticationProviderId", "ExternalId")
                        .IsUnique();

                    b.ToTable("user_identities", "auditarium");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", "auditarium");
                });

            modelBuilder.Entity("Auditarium.Models.Jobs.JobRuntimeState", b =>
                {
                    b.Property<string>("JobKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("job_key");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset?>("LastCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_completed_at");

                    b.Property<string>("LastResult")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_result");

                    b.Property<DateTimeOffset?>("LastStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_started_at");

                    b.Property<string>("LastStartupVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_startup_version");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<string>("RunningInstanceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("running_instance_id");

                    b.HasKey("JobKey");

                    b.ToTable("job_runtime_state", "auditarium");
                });

            modelBuilder.Entity("Auditarium.Models.Catalog.Audit", b =>
                {
                    b.HasOne("Auditarium.Models.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedAuditorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Auditarium.Models.Catalog.AuditUnit", null)
                        .WithMany()
                        .HasForeignKey("AuditUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auditarium.Models.Catalog.CatalogVersion", null)
                        .WithMany()
                        .HasForeignKey("CatalogVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auditarium.Models.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Auditarium.Models.Catalog.Audit", null)
                        .WithMany()
                        .HasForeignKey("OriginAuditId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Auditarium.Models.Catalog.AuditDocumentElement", b =>
                {
                    b.HasOne("Auditarium.Models.Catalog.Audit", null)
                        .WithMany()
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auditarium.Models.Catalog.DocumentElement", null)
                        .WithMany()
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auditarium.Models.Catalog.AuditQuestion", b =>
                {
                    b.HasOne("Auditarium.Models.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("AnsweredBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Auditarium.Models.Catalog.AuditDocumentElement", null)
                        .WithMany()
                        .HasForeignKey("AuditDocumentElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auditarium.Models.Catalog.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auditarium.Models.Catalog.AuditUnit", b =>
                {
                    b.HasOne("Auditarium.Models.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Auditarium.Models.Catalog.AuditUnit", null)
                        .WithMany()
                        .HasForeignKey("ParentAuditUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Auditarium.Models.Catalog.ScopeType", null)
                        .WithMany()
                        .HasForeignKey("ScopeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auditarium.Models.Catalog.CatalogVersion", b =>
                {
                    b.HasOne("Auditarium.Models.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auditarium.Models.Catalog.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auditarium.Models.Catalog.FileItem", null)
                        .WithMany()
                        .HasForeignKey("SourceFileId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Auditarium.Models.Catalog.Document", b =>
                {
                    b.HasOne("Auditarium.Models.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Auditarium.Models.Catalog.DocumentElement", b =>
                {
                    b.HasOne("Auditarium.Models.Catalog.CatalogVersion", null)
                        .WithMany()
                        .HasForeignKey("CatalogVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auditarium.Models.Catalog.DocumentElement", "ParentElement")
                        .WithMany()
                        .HasForeignKey("ParentElementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentElement");
                });

            modelBuilder.Entity("Auditarium.Models.Catalog.DocumentElementWeight", b =>
                {
                    b.HasOne("Auditarium.Models.Catalog.DocumentElement", "Element")
                        .WithMany()
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");
                });

            modelBuilder.Entity("Auditarium.Models.Catalog.FileItem", b =>
                {
                    b.HasOne("Auditarium.Models.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auditarium.Models.Catalog.Question", b =>
                {
                    b.HasOne("Auditarium.Models.Catalog.DocumentElement", "Element")
                        .WithMany()
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");
                });

            modelBuilder.Entity("Auditarium.Models.Catalog.QuestionScopeType", b =>
                {
                    b.HasOne("Auditarium.Models.Catalog.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auditarium.Models.Catalog.ScopeType", "ScopeType")
                        .WithMany()
                        .HasForeignKey("ScopeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("ScopeType");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.ApiCredential", b =>
                {
                    b.HasOne("Auditarium.Models.Identity.UserIdentity", "Identity")
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.LocalCredential", b =>
                {
                    b.HasOne("Auditarium.Models.Identity.UserIdentity", "Identity")
                        .WithOne("LocalCredential")
                        .HasForeignKey("Auditarium.Models.Identity.LocalCredential", "IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.RolePermission", b =>
                {
                    b.HasOne("Auditarium.Models.Identity.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auditarium.Models.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Auditarium.Models.Identity.SystemAuditLog", b =>
                {
                    b.HasOne("Auditarium.Models.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auditarium.Models.Identity.UserIdentity", b =>
                {
                    b.HasOne("Auditarium.Models.Identity.AuthenticationProvider", "AuthenticationProvider")
                        .WithMany()
                        .HasForeignKey("AuthenticationProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auditarium.Models.Identity.User", "User")
                        .WithMany("Identities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthenticationProvider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.UserRole", b =>
                {
                    b.HasOne("Auditarium.Models.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auditarium.Models.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auditarium.Models.Identity.User", b =>
                {
                    b.Navigation("Identities");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.UserIdentity", b =>
                {
                    b.Navigation("LocalCredential");
                });
#pragma warning restore 612, 618
        }
    }
}
