// <auto-generated />
using System;
using Auditarium.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Auditarium.Dal.PostgreSql.Migrations.Migrations
{
    [DbContext(typeof(AuditariumDbContext))]
    [Migration("20260919155240_InitialBootstrap")]
    partial class InitialBootstrap
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("auditarium")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Auditarium.Models.Identity.ApplicationSetting", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("setting_key");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<string>("SerializedValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serialized_value");

                    b.HasKey("SettingKey");

                    b.ToTable("application_settings", "auditarium");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.AuthenticationProvider", b =>
                {
                    b.Property<long>("AuthenticationProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("authentication_provider_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuthenticationProviderId"));

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_type");

                    b.HasKey("AuthenticationProviderId");

                    b.HasIndex("ProviderKey")
                        .IsUnique();

                    b.ToTable("authentication_providers", "auditarium");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.LocalCredential", b =>
                {
                    b.Property<long>("IdentityId")
                        .HasColumnType("bigint")
                        .HasColumnName("identity_id");

                    b.Property<int>("FailedAttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempt_count");

                    b.Property<DateTimeOffset?>("FailedAttemptWindowStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_attempt_window_started_at");

                    b.Property<DateTimeOffset?>("LockoutUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_until");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<DateTimeOffset?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("IdentityId");

                    b.ToTable("local_credentials", "auditarium");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.Permission", b =>
                {
                    b.Property<string>("PermissionKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("permission_key");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("PermissionKey");

                    b.ToTable("permissions", "auditarium");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RoleId"));

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("RoleKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role_key");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleKey")
                        .IsUnique()
                        .HasFilter("role_key IS NOT NULL");

                    b.ToTable("roles", "auditarium");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.RolePermission", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<string>("PermissionKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("permission_key");

                    b.HasKey("RoleId", "PermissionKey");

                    b.HasIndex("PermissionKey");

                    b.ToTable("role_permissions", "auditarium");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("UserKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_key");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("UserKey")
                        .IsUnique()
                        .HasFilter("user_key IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", "auditarium");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.UserIdentity", b =>
                {
                    b.Property<long>("IdentityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("identity_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdentityId"));

                    b.Property<long>("AuthenticationProviderId")
                        .HasColumnType("bigint")
                        .HasColumnName("authentication_provider_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("IdentityId");

                    b.HasIndex("UserId");

                    b.HasIndex("AuthenticationProviderId", "ExternalId")
                        .IsUnique();

                    b.ToTable("user_identities", "auditarium");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", "auditarium");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.LocalCredential", b =>
                {
                    b.HasOne("Auditarium.Models.Identity.UserIdentity", "Identity")
                        .WithOne("LocalCredential")
                        .HasForeignKey("Auditarium.Models.Identity.LocalCredential", "IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.RolePermission", b =>
                {
                    b.HasOne("Auditarium.Models.Identity.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auditarium.Models.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Auditarium.Models.Identity.UserIdentity", b =>
                {
                    b.HasOne("Auditarium.Models.Identity.AuthenticationProvider", "AuthenticationProvider")
                        .WithMany()
                        .HasForeignKey("AuthenticationProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auditarium.Models.Identity.User", "User")
                        .WithMany("Identities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthenticationProvider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.UserRole", b =>
                {
                    b.HasOne("Auditarium.Models.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Auditarium.Models.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Auditarium.Models.Identity.User", b =>
                {
                    b.Navigation("Identities");
                });

            modelBuilder.Entity("Auditarium.Models.Identity.UserIdentity", b =>
                {
                    b.Navigation("LocalCredential");
                });
#pragma warning restore 612, 618
        }
    }
}
